-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks_Global by shawn.johnson@sqldbm.com **


-- ************************************** lnk_
CREATE TABLE lnk_
(
 md5_lnk_                    binary NOT NULL,
 PARENT_DEPARTMENT_GROUP_KEY number(38,0),
 md5_hub_                    binary NOT NULL,
 load_dts                    timestamp_ntz(9) NOT NULL,
 rec_src                     varchar(16777216) NOT NULL,
 ld_dt                       varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_1 PRIMARY KEY ( md5_lnk_ )
);

-- ************************************** SHAWN_ADWORKS.DIM_SCENARIO
CREATE TABLE SHAWN_ADWORKS.DIM_SCENARIO
(
 SCENARIO_KEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 SCENARIO_NAME varchar(50) COMMENT 'Name of the Scenario',
 CREATED_BY    varchar(50) NOT NULL COMMENT 'Who Created this Scenario',
 CREATED_DATE  timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 UPDATED_DATE  timestamp_ntz(9) NOT NULL,
 UPDATED_BY    varchar(50) NOT NULL,
 TEST_COL      varchar(50) NOT NULL,
 ld_dt         varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_SCENARIO PRIMARY KEY ( SCENARIO_KEY )
)
COMMENT = 'Dimension Scenario';

-- ************************************** SHAWN_ADWORKS.DIM_SALES_TERRITORY
CREATE TABLE SHAWN_ADWORKS.DIM_SALES_TERRITORY
(
 SALES_TERRITORY_KEY           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SALES_TERRITORY_ALTERNATE_KEY number(38,0),
 SALES_TERRITORY_REGION        varchar(50) NOT NULL,
 SALES_TERRITORY_COUNTRY       varchar(50) NOT NULL,
 SALES_TERRITORY_GROUP         varchar(50),
 ld_dt                         varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_SALES_TERRITORY PRIMARY KEY ( SALES_TERRITORY_KEY )
)
COMMENT = 'Sales Territory data';

-- ************************************** SHAWN_ADWORKS.DIM_PROMOTION
CREATE TABLE SHAWN_ADWORKS.DIM_PROMOTION
(
 PROMOTION_KEY              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PROMOTION_ALTERNATE_KEY    number(38,0),
 ENGLISH_PROMOTION_NAME     varchar(255),
 SPANISH_PROMOTION_NAME     varchar(255),
 FRENCH_PROMOTION_NAME      varchar(255),
 DISCOUNT_PCT               float,
 ENGLISH_PROMOTION_TYPE     varchar(50),
 SPANISH_PROMOTION_TYPE     varchar(50),
 FRENCH_PROMOTION_TYPE      varchar(50),
 ENGLISH_PROMOTION_CATEGORY varchar(50),
 SPANISH_PROMOTION_CATEGORY varchar(50),
 FRENCH_PROMOTION_CATEGORY  varchar(50),
 MIN_QTY                    number(38,0),
 MAX_QTY                    number(38,0),
 ld_dt                      varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_PROMOTION PRIMARY KEY ( PROMOTION_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_PRODUCT_CATEGORY
CREATE TABLE SHAWN_ADWORKS.DIM_PRODUCT_CATEGORY
(
 PRODUCT_CATEGORY_KEY           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PRODUCT_CATEGORY_ALTERNATE_KEY number(38,0),
 ENGLISH_PRODUCT_CATEGORY_NAME  varchar(50) NOT NULL,
 SPANISH_PRODUCT_CATEGORY_NAME  varchar(50) NOT NULL,
 FRENCH_PRODUCT_CATEGORY_NAME   varchar(50) NOT NULL,
 ld_dt                          varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_PRODUCT_CATEGORY PRIMARY KEY ( PRODUCT_CATEGORY_KEY )
);

-- ************************************** SHAWN_ADWORKS.dim_DIM_DEPARTMENT_GROUP
CREATE TABLE SHAWN_ADWORKS.dim_DIM_DEPARTMENT_GROUP
(
 DEPARTMENT_GROUP_KEY        number(38,0) NOT NULL,
 from_dts                    timestamp_ntz(9) NOT NULL,
 to_dts                      timestamp_ntz(9) NOT NULL,
 PARENT_DEPARTMENT_GROUP_KEY number(38,0),
 DEPARTMENT_GROUP_NAME       varchar(50),
 load_dts                    timestamp_ntz(9) NOT NULL,
 ld_dt                       varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_1 PRIMARY KEY ( DEPARTMENT_GROUP_KEY, from_dts )
);

-- ************************************** SHAWN_ADWORKS.DIM_DEPARTMENT_GROUP
CREATE TABLE SHAWN_ADWORKS.DIM_DEPARTMENT_GROUP
(
 DEPARTMENT_GROUP_KEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DEPARTMENT_GROUP_NAME varchar(50),
 ld_dt                 varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_DEPARTMENT_GROUP PRIMARY KEY ( DEPARTMENT_GROUP_KEY )
)
COMMENT = 'Dimension for Department groups';

-- ************************************** SHAWN_ADWORKS.DIM_DATE
CREATE TABLE SHAWN_ADWORKS.DIM_DATE
(
 DATE_KEY                 number(38,0) NOT NULL,
 FULL_DATE_ALTERNATE_KEY  date NOT NULL,
 DAY_NUMBER_OF_WEEK       number(38,0) NOT NULL,
 ENGLISH_DAY_NAME_OF_WEEK varchar(10) NOT NULL,
 SPANISH_DAY_NAME_OF_WEEK varchar(10) NOT NULL,
 FRENCH_DAY_NAME_OF_WEEK  varchar(10) NOT NULL,
 DAY_NUMBER_OF_MONTH      number(38,0) NOT NULL,
 DAY_NUMBER_OF_YEAR       number(38,0) NOT NULL,
 WEEK_NUMBER_OF_YEAR      number(38,0) NOT NULL,
 ENGLISH_MONTH_NAME       varchar(10) NOT NULL,
 SPANISH_MONTH_NAME       varchar(10) NOT NULL,
 FRENCH_MONTH_NAME        varchar(10) NOT NULL,
 MONTH_NUMBER_OF_YEAR     number(38,0) NOT NULL,
 CALENDAR_QUARTER         number(38,0) NOT NULL,
 CALENDAR_YEAR            number(38,0) NOT NULL,
 CALENDAR_SEMESTER        number(38,0) NOT NULL,
 FISCAL_QUARTER           number(38,0) NOT NULL,
 FISCAL_YEAR              number(38,0) NOT NULL,
 FISCAL_SEMESTER          number(38,0) NOT NULL,
 ld_dt                    varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_1 PRIMARY KEY ( DATE_KEY )
)
COMMENT = 'Dimension for Date time';

-- ************************************** SHAWN_ADWORKS.DIM_CURRENCY
CREATE TABLE SHAWN_ADWORKS.DIM_CURRENCY
(
 CURRENCY_KEY           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 CURRENCY_ALTERNATE_KEY varchar(3) NOT NULL COMMENT 'Alternate Currency Identifier',
 CURRENCY_NAME          varchar(50) NOT NULL COMMENT 'Name of the Currency',
 ld_dt                  varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_CURRENCY PRIMARY KEY ( CURRENCY_KEY )
)
COMMENT = 'Dimension for Currency Data';

-- ************************************** SHAWN_ADWORKS.DIM_ACCOUNT
CREATE TABLE SHAWN_ADWORKS.DIM_ACCOUNT
(
 ACCOUNT_KEY                       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 PARENT_ACCOUNT_KEY                number(38,0) COMMENT 'Identifier of parent Account',
 ACCOUNT_CODE_ALTERNATE_KEY        number(38,0),
 PARENT_ACCOUNT_CODE_ALTERNATE_KEY number(38,0),
 ACCOUNT_DESCRIPTION               varchar(50),
 ACCOUNT_TYPE                      varchar(50),
 OPERATOR                          varchar(50),
 CUSTOM_MEMBERS                    varchar(300),
 VALUE_TYPE                        varchar(50),
 CUSTOM_MEMBER_OPTIONS             varchar(200),
 ld_dt                             varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_ACCOUNT PRIMARY KEY ( ACCOUNT_KEY ) RELY
)
COMMENT = 'Holds all Account information';

-- ************************************** TABLE_27
CREATE TABLE TABLE_27
(
 md5_lnk_ binary NOT NULL,
 ld_dt    varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_38 FOREIGN KEY ( md5_lnk_ ) REFERENCES lnk_ ( md5_lnk_ )
);

-- ************************************** SHAWN_ADWORKS.NEW_FACT_CURRENCY_RATE
CREATE TABLE SHAWN_ADWORKS.NEW_FACT_CURRENCY_RATE
(
 AVERAGE_RATE    float,
 CURRENCY_ID     varchar(3),
 CURRENCY_DATE   date,
 END_OF_DAY_RATE float,
 CURRENCY_KEY    number(38,0),
 DATE_KEY        number(38,0) NOT NULL,
 ld_dt           varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_NEW_FACT_CURRENCY_RATE_469 FOREIGN KEY ( CURRENCY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_CURRENCY ( CURRENCY_KEY ),
 CONSTRAINT FK_NEW_FACT_CURRENCY_RATE_471 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
);

-- ************************************** SHAWN_ADWORKS.FACT_CURRENCY_RATE
CREATE TABLE SHAWN_ADWORKS.FACT_CURRENCY_RATE
(
 CURRENCY_KEY    number(38,0) NOT NULL,
 AVERAGE_RATE    float NOT NULL,
 END_OF_DAY_RATE float NOT NULL,
 DATE_KEY        number(38,0) NOT NULL,
 ld_dt           varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_CURRENCY_RATE_413 FOREIGN KEY ( CURRENCY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_CURRENCY ( CURRENCY_KEY ),
 CONSTRAINT FK_FACT_CURRENCY_RATE_415 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_PRODUCT_SUBCATEGORY
CREATE TABLE SHAWN_ADWORKS.DIM_PRODUCT_SUBCATEGORY
(
 PRODUCT_SUBCATEGORY_KEY           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PRODUCT_SUBCATEGORY_ALTERNATE_KEY number(38,0),
 ENGLISH_PRODUCT_SUBCATEGORY_NAME  varchar(50) NOT NULL,
 SPANISH_PRODUCT_SUBCATEGORY_NAME  varchar(50) NOT NULL,
 FRENCH_PRODUCT_SUBCATEGORY_NAME   varchar(50) NOT NULL,
 PRODUCT_CATEGORY_KEY              number(38,0),
 ld_dt                             varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_PRODUCT_SUBCATEGORY PRIMARY KEY ( PRODUCT_SUBCATEGORY_KEY ),
 CONSTRAINT FK_DIM_PRODUCT_SUBCATEGORY_409 FOREIGN KEY ( PRODUCT_CATEGORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PRODUCT_CATEGORY ( PRODUCT_CATEGORY_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_ORGANIZATION
CREATE TABLE SHAWN_ADWORKS.DIM_ORGANIZATION
(
 ORGANIZATION_KEY        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PARENT_ORGANIZATION_KEY number(38,0),
 PERCENTAGE_OF_OWNERSHIP varchar(16),
 ORGANIZATION_NAME       varchar(50),
 CURRENCY_KEY            number(38,0),
 ld_dt                   varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_ORGANIZATION PRIMARY KEY ( ORGANIZATION_KEY )
)
COMMENT = 'Dimension for Organizational Data';

-- ************************************** SHAWN_ADWORKS.DIM_GEOGRAPHY
CREATE TABLE SHAWN_ADWORKS.DIM_GEOGRAPHY
(
 GEOGRAPHY_KEY               number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 CITY                        varchar(30),
 STATE_PROVINCE_CODE         varchar(3),
 STATE_PROVINCE_NAME         varchar(50),
 COUNTRY_REGION_CODE         varchar(3),
 ENGLISH_COUNTRY_REGION_NAME varchar(50),
 SPANISH_COUNTRY_REGION_NAME varchar(50),
 FRENCH_COUNTRY_REGION_NAME  varchar(50),
 POSTAL_CODE                 varchar(15),
 SALES_TERRITORY_KEY         number(38,0),
 IP_ADDRESS_LOCATOR          varchar(15),
 ld_dt                       varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_GEOGRAPHY PRIMARY KEY ( GEOGRAPHY_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_EMPLOYEE
CREATE TABLE SHAWN_ADWORKS.DIM_EMPLOYEE
(
 EMPLOYEE_KEY                              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PARENT_EMPLOYEE_KEY                       number(38,0),
 EMPLOYEE_NATIONAL_ID_ALTERNATE_KEY        varchar(15),
 PARENT_EMPLOYEE_NATIONAL_ID_ALTERNATE_KEY varchar(15),
 SALES_TERRITORY_KEY                       number(38,0),
 FIRST_NAME                                varchar(50) NOT NULL,
 LAST_NAME                                 varchar(50) NOT NULL,
 MIDDLE_NAME                               varchar(50),
 NAME_STYLE                                number(38,0) NOT NULL,
 TITLE                                     varchar(50),
 HIRE_DATE                                 date,
 BIRTH_DATE                                date,
 LOGIN_ID                                  varchar(256),
 EMAIL_ADDRESS                             varchar(50),
 PHONE                                     varchar(25),
 MARITAL_STATUS                            varchar(1),
 EMERGENCY_CONTACT_NAME                    varchar(50),
 EMERGENCY_CONTACT_PHONE                   varchar(25),
 SALARIED_FLAG                             number(38,0),
 GENDER                                    varchar(1),
 PAY_FREQUENCY                             number(38,0),
 BASE_RATE                                 number(38,0),
 VACATION_HOURS                            number(38,0),
 SICK_LEAVE_HOURS                          number(38,0),
 CURRENT_FLAG                              number(38,0) NOT NULL,
 SALES_PERSON_FLAG                         number(38,0) NOT NULL,
 DEPARTMENT_NAME                           varchar(50),
 START_DATE                                date,
 END_DATE                                  date,
 STATUS                                    varchar(50),
 ld_dt                                     varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_EMPLOYEE PRIMARY KEY ( EMPLOYEE_KEY ),
 CONSTRAINT FK_DIM_EMPLOYEE_403 FOREIGN KEY ( PARENT_EMPLOYEE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_EMPLOYEE ( EMPLOYEE_KEY ),
 CONSTRAINT FK_DIM_EMPLOYEE_405 FOREIGN KEY ( SALES_TERRITORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_SALES_TERRITORY ( SALES_TERRITORY_KEY )
)
COMMENT = 'This table holds all Employee Information';

-- ************************************** SHAWN_ADWORKS.CHILD_DEMO
CREATE TABLE SHAWN_ADWORKS.CHILD_DEMO
(
 SCENARIO_KEY number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 CREATED_BY   varchar(50) NOT NULL,
 CREATED_DATE timestamp_ntz(9) NOT NULL,
 UPDATED_DATE timestamp_ntz(9) NOT NULL,
 UPDATED_BY   varchar(50) NOT NULL,
 ld_dt        varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_664 PRIMARY KEY ( SCENARIO_KEY ) RELY,
 CONSTRAINT FK_661 FOREIGN KEY ( SCENARIO_KEY ) REFERENCES SHAWN_ADWORKS.DIM_SCENARIO ( SCENARIO_KEY ) RELY
);

-- ************************************** SHAWN_ADWORKS.FACT_SALES_QUOTA
CREATE TABLE SHAWN_ADWORKS.FACT_SALES_QUOTA
(
 SALES_QUOTA_KEY    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 EMPLOYEE_KEY       number(38,0) NOT NULL,
 CALENDAR_YEAR      number(38,0) NOT NULL,
 CALENDAR_QUARTER   number(38,0) NOT NULL,
 SALES_AMOUNT_QUOTA number(38,0) NOT NULL,
 DATE_KEY           number(38,0) NOT NULL,
 ld_dt              varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_SALES_QUOTA_463 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
);

-- ************************************** SHAWN_ADWORKS.FACT_FINANCE
CREATE TABLE SHAWN_ADWORKS.FACT_FINANCE
(
 FINANCE_KEY          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ORGANIZATION_KEY     number(38,0) NOT NULL,
 DEPARTMENT_GROUP_KEY number(38,0) NOT NULL,
 SCENARIO_KEY         number(38,0) NOT NULL,
 ACCOUNT_KEY          number(38,0) NOT NULL,
 AMOUNT               float NOT NULL,
 DATE_KEY             number(38,0) NOT NULL,
 ld_dt                varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_FINANCE_417 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_FINANCE_419 FOREIGN KEY ( ORGANIZATION_KEY ) REFERENCES SHAWN_ADWORKS.DIM_ORGANIZATION ( ORGANIZATION_KEY ),
 CONSTRAINT FK_FACT_FINANCE_421 FOREIGN KEY ( DEPARTMENT_GROUP_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DEPARTMENT_GROUP ( DEPARTMENT_GROUP_KEY ),
 CONSTRAINT FK_FACT_FINANCE_423 FOREIGN KEY ( SCENARIO_KEY ) REFERENCES SHAWN_ADWORKS.DIM_SCENARIO ( SCENARIO_KEY ),
 CONSTRAINT FK_FACT_FINANCE_425 FOREIGN KEY ( ACCOUNT_KEY ) REFERENCES SHAWN_ADWORKS.DIM_ACCOUNT ( ACCOUNT_KEY )
)
COMMENT = 'Facts for Finance';

-- ************************************** SHAWN_ADWORKS.DIM_RESELLER
CREATE TABLE SHAWN_ADWORKS.DIM_RESELLER
(
 RESELLER_KEY           number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 GEOGRAPHY_KEY          number(38,0),
 RESELLER_ALTERNATE_KEY varchar(15),
 PHONE                  varchar(25),
 BUSINESS_TYPE          varchar(20) NOT NULL,
 RESELLER_NAME          varchar(50) NOT NULL,
 NUMBER_EMPLOYEES       number(38,0),
 ORDER_FREQUENCY        varchar(1),
 ORDER_MONTH            number(38,0),
 FIRST_ORDER_YEAR       number(38,0),
 LAST_ORDER_YEAR        number(38,0),
 PRODUCT_LINE           varchar(50),
 ADDRESS_LINE_1         varchar(60),
 ADDRESS_LINE_2         varchar(60),
 ANNUAL_SALES           number(38,0),
 BANK_NAME              varchar(50),
 MIN_PAYMENT_TYPE       number(38,0),
 MIN_PAYMENT_AMOUNT     number(38,0),
 ANNUAL_REVENUE         number(38,0),
 YEAR_OPENED            number(38,0),
 ld_dt                  varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_RESELLER PRIMARY KEY ( RESELLER_KEY ),
 CONSTRAINT FK_DIM_RESELLER_411 FOREIGN KEY ( GEOGRAPHY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_GEOGRAPHY ( GEOGRAPHY_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_PRODUCT
CREATE TABLE SHAWN_ADWORKS.DIM_PRODUCT
(
 PRODUCT_KEY              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PRODUCT_ALTERNATE_KEY    varchar(25),
 PRODUCT_SUBCATEGORY_KEY  number(38,0),
 WEIGHT_UNIT_MEASURE_CODE varchar(3),
 SIZE_UNIT_MEASURE_CODE   varchar(3),
 ENGLISH_PRODUCT_NAME     varchar(50) NOT NULL,
 SPANISH_PRODUCT_NAME     varchar(50),
 FRENCH_PRODUCT_NAME      varchar(50),
 STANDARD_COST            number(38,0),
 FINISHED_GOODS_FLAG      number(38,0) NOT NULL,
 COLOR                    varchar(15) NOT NULL,
 SAFETY_STOCK_LEVEL       number(38,0),
 REORDER_POINT            number(38,0),
 LIST_PRICE               number(38,0),
 SIZE                     varchar(50),
 SIZE_RANGE               varchar(50),
 WEIGHT                   float,
 DAYS_TO_MANUFACTURE      number(38,0),
 PRODUCT_LINE             varchar(2),
 DEALER_PRICE             number(38,0),
 CLASS                    varchar(2),
 STYLE                    varchar(2),
 MODEL_NAME               varchar(50),
 ENGLISH_DESCRIPTION      varchar(400),
 FRENCH_DESCRIPTION       varchar(400),
 CHINESE_DESCRIPTION      varchar(400),
 ARABIC_DESCRIPTION       varchar(400),
 HEBREW_DESCRIPTION       varchar(400),
 THAI_DESCRIPTION         varchar(400),
 GERMAN_DESCRIPTION       varchar(400),
 JAPANESE_DESCRIPTION     varchar(400),
 TURKISH_DESCRIPTION      varchar(400),
 STATUS                   varchar(7),
 ld_dt                    varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY ( PRODUCT_KEY ),
 CONSTRAINT FK_DIM_PRODUCT_407 FOREIGN KEY ( PRODUCT_SUBCATEGORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PRODUCT_SUBCATEGORY ( PRODUCT_SUBCATEGORY_KEY )
);

-- ************************************** SHAWN_ADWORKS.DIM_CUSTOMER
CREATE TABLE SHAWN_ADWORKS.DIM_CUSTOMER
(
 CUSTOMER_KEY            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 GEOGRAPHY_KEY           number(38,0) COMMENT 'Geographic informatio',
 CUSTOMER_ALTERNATE_KEY  varchar(15) NOT NULL COMMENT 'Alternate Key',
 TITLE                   varchar(8) COMMENT 'Title of the Customer',
 FIRST_NAME              varchar(50),
 MIDDLE_NAME             varchar(50),
 LAST_NAME               varchar(50),
 NAME_STYLE              varchar(5),
 BIRTH_DATE              date,
 MARITAL_STATUS          varchar(1),
 SUFFIX                  varchar(10),
 GENDER                  varchar(1),
 EMAIL_ADDRESS           varchar(50),
 YEARLY_INCOME           number(38,0),
 TOTAL_CHILDREN          number(38,0),
 NUMBER_CHILDREN_AT_HOME number(38,0),
 ENGLISH_EDUCATION       varchar(40),
 SPANISH_EDUCATION       varchar(40),
 FRENCH_EDUCATION        varchar(40),
 ENGLISH_OCCUPATION      varchar(100),
 SPANISH_OCCUPATION      varchar(100),
 FRENCH_OCCUPATION       varchar(100),
 HOUSE_OWNER_FLAG        varchar(1),
 NUMBER_CARS_OWNED       number(38,0),
 ADDRESS_LINE            varchar(120),
 ADDRESS_LINE_2          varchar(120),
 PHONE                   varchar(20),
 DATE_FIRST_PURCHASE     date,
 COMMUTE_DISTANCE        varchar(15),
 NEW_COL                 varchar(50) NOT NULL,
 ld_dt                   varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY ( CUSTOMER_KEY ),
 CONSTRAINT FK_DIM_CUSTOMER_401 FOREIGN KEY ( GEOGRAPHY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_GEOGRAPHY ( GEOGRAPHY_KEY )
)
COMMENT = 'Dimension for Customer Data';

-- ************************************** SHAWN_ADWORKS.FACT_SURVEY_RESPONSE
CREATE TABLE SHAWN_ADWORKS.FACT_SURVEY_RESPONSE
(
 SURVEY_RESPONSE_KEY              number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 CUSTOMER_KEY                     number(38,0) NOT NULL,
 PRODUCT_CATEGORY_KEY             number(38,0) NOT NULL,
 ENGLISH_PRODUCT_CATEGORY_NAME    varchar(50) NOT NULL,
 PRODUCT_SUBCATEGORY_KEY          number(38,0) NOT NULL,
 ENGLISH_PRODUCT_SUBCATEGORY_NAME varchar(50) NOT NULL,
 DATE_KEY                         number(38,0) NOT NULL,
 ld_dt                            varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_SURVEY_RESPONSE_465 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_SURVEY_RESPONSE_467 FOREIGN KEY ( PRODUCT_CATEGORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PRODUCT_CATEGORY ( PRODUCT_CATEGORY_KEY )
);

-- ************************************** SHAWN_ADWORKS.FACT_RESELLER_SALES
CREATE TABLE SHAWN_ADWORKS.FACT_RESELLER_SALES
(
 PRODUCT_KEY             number(38,0) NOT NULL,
 RESELLER_KEY            number(38,0) NOT NULL,
 EMPLOYEE_KEY            number(38,0) NOT NULL,
 PROMOTION_KEY           number(38,0) NOT NULL,
 CURRENCY_KEY            number(38,0) NOT NULL,
 SALES_TERRITORY_KEY     number(38,0) NOT NULL,
 SALES_ORDER_NUMBER      varchar(20) NOT NULL,
 SALES_ORDER_LINE_NUMBER number(38,0) NOT NULL,
 REVISION_NUMBER         number(38,0),
 ORDER_QUANTITY          number(38,0),
 UNIT_PRICE              number(38,0),
 EXTENDED_AMOUNT         number(38,0),
 UNIT_PRICE_DISCOUNT_PCT float,
 DISCOUNT_AMOUNT         float,
 PRODUCT_STANDARD_COST   number(38,0),
 TOTAL_PRODUCT_COST      number(38,0),
 SALES_AMOUNT            number(38,0),
 TAX_AMT                 number(38,0),
 FREIGHT                 number(38,0),
 CARRIER_TRACKING_NUMBER varchar(25),
 CUSTOMER_PO_NUMBER      varchar(25),
 DATE_KEY                number(38,0) NOT NULL,
 DKEY_1                  number(38,0) NOT NULL,
 DKEY_2                  number(38,0) NOT NULL,
 ld_dt                   varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_RESELLER_SALES_445 FOREIGN KEY ( PRODUCT_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PRODUCT ( PRODUCT_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_447 FOREIGN KEY ( RESELLER_KEY ) REFERENCES SHAWN_ADWORKS.DIM_RESELLER ( RESELLER_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_449 FOREIGN KEY ( EMPLOYEE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_EMPLOYEE ( EMPLOYEE_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_451 FOREIGN KEY ( PROMOTION_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PROMOTION ( PROMOTION_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_453 FOREIGN KEY ( CURRENCY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_CURRENCY ( CURRENCY_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_455 FOREIGN KEY ( SALES_TERRITORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_SALES_TERRITORY ( SALES_TERRITORY_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_457 FOREIGN KEY ( DKEY_1 ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_459 FOREIGN KEY ( DKEY_2 ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_RESELLER_SALES_461 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
)
COMMENT = 'Fact data of Reseller Sales';

-- ************************************** SHAWN_ADWORKS.FACT_PRODUCT_INVENTORY
CREATE TABLE SHAWN_ADWORKS.FACT_PRODUCT_INVENTORY
(
 PRODUCT_KEY   number(38,0) NOT NULL,
 MOVEMENT_DATE date NOT NULL,
 UNIT_COST     number(38,0) NOT NULL,
 UNITS_IN      number(38,0) NOT NULL,
 UNITS_OUT     number(38,0) NOT NULL,
 UNITS_BALANCE number(38,0) NOT NULL,
 DATE_KEY      number(38,0) NOT NULL,
 ld_dt         varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_PRODUCT_INVENTORY_443 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
);

-- ************************************** SHAWN_ADWORKS.FACT_INTERNET_SALES
CREATE TABLE SHAWN_ADWORKS.FACT_INTERNET_SALES
(
 PRODUCT_KEY             number(38,0) NOT NULL,
 CUSTOMER_KEY            number(38,0) NOT NULL,
 PROMOTION_KEY           number(38,0) NOT NULL,
 CURRENCY_KEY            number(38,0) NOT NULL,
 SALES_TERRITORY_KEY     number(38,0) NOT NULL,
 SALES_ORDER_NUMBER      varchar(20) NOT NULL,
 SALES_ORDER_LINE_NUMBER number(38,0) NOT NULL,
 REVISION_NUMBER         number(38,0) NOT NULL,
 ORDER_QUANTITY          number(38,0) NOT NULL,
 UNIT_PRICE              number(38,0) NOT NULL,
 EXTENDED_AMOUNT         number(38,0) NOT NULL,
 UNIT_PRICE_DISCOUNT_PCT float NOT NULL,
 DISCOUNT_AMOUNT         float NOT NULL,
 PRODUCT_STANDARD_COST   number(38,0) NOT NULL,
 TOTAL_PRODUCT_COST      number(38,0) NOT NULL,
 SALES_AMOUNT            number(38,0) NOT NULL,
 TAX_AMT                 number(38,0) NOT NULL,
 FREIGHT                 number(38,0) NOT NULL,
 CARRIER_TRACKING_NUMBER varchar(25),
 CUSTOMER_PO_NUMBER      varchar(25),
 DATE_KEY                number(38,0) NOT NULL,
 DKEY_1                  number(38,0) NOT NULL,
 DKEY_2                  number(38,0) NOT NULL,
 ld_dt                   varchar(50) NOT NULL, -- From template: "Dates"

 CONSTRAINT FK_FACT_INTERNET_SALES_427 FOREIGN KEY ( PRODUCT_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PRODUCT ( PRODUCT_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_429 FOREIGN KEY ( CUSTOMER_KEY ) REFERENCES SHAWN_ADWORKS.DIM_CUSTOMER ( CUSTOMER_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_431 FOREIGN KEY ( PROMOTION_KEY ) REFERENCES SHAWN_ADWORKS.DIM_PROMOTION ( PROMOTION_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_433 FOREIGN KEY ( CURRENCY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_CURRENCY ( CURRENCY_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_435 FOREIGN KEY ( SALES_TERRITORY_KEY ) REFERENCES SHAWN_ADWORKS.DIM_SALES_TERRITORY ( SALES_TERRITORY_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_437 FOREIGN KEY ( DKEY_2 ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_439 FOREIGN KEY ( DATE_KEY ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT FK_FACT_INTERNET_SALES_441 FOREIGN KEY ( DKEY_1 ) REFERENCES SHAWN_ADWORKS.DIM_DATE ( DATE_KEY )
)
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** SHAWN_ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V
CREATE VIEW SQLDBM_DEMO.SHAWN_ADWORKS.DIM_PRODUCT_CAT_SUBCAT_V(
	"ProductKey",
	"ProductAlternateKey",
	"ProductSubcategoryKey",
	"WeightUnitMeasureCode",
	"SizeUnitMeasureCode",
	"EnglishProductName",
	"StandardCost",
	"FinishedGoodsFlag",
	"Color",
	"SafetyStockLevel",
	"ReorderPoint",
	"ListPrice",
	"Size",
	"SizeRange",
	"Weight",
	"DaysToManufacture",
	"ProductLine",
	"DealerPrice",
	"Class",
	"Style",
	"ModelName",
	"EnglishDescription",
	"Status",
	"ProductCategoryKey",
	"ProductCategoryAlternateKey",
	"EnglishProductCategoryName",
	"EnglishProductSubcategoryName"
) COMMENT='Product details with cat and subcat english names. For fwd/rev engineering'
 as
(
WITH cat_subcat as (
SELECT cat.* , sub."ProductSubcategoryKey" as "SubProductSubcategoryKey", sub."EnglishProductSubcategoryName"  FROM "DimProductCategory" cat
inner join  "DimProductSubcategory" sub
on  cat."ProductCategoryKey" = sub."ProductCategoryKey"
) 
  select 
 "ProductKey"           
, "ProductAlternateKey"  
, "ProductSubcategoryKey"
, "WeightUnitMeasureCode"
, "SizeUnitMeasureCode"  
, "EnglishProductName"   
, "StandardCost"         
, "FinishedGoodsFlag"    
, "Color"                
, "SafetyStockLevel"     
, "ReorderPoint"         
, "ListPrice"            
, "Size"                 
 ,"SizeRange"            
 ,"Weight"               
 ,"DaysToManufacture"    
 ,"ProductLine"          
 ,"DealerPrice"          
 ,"Class"                
 ,"Style"                
 ,"ModelName"            
 ,"EnglishDescription"   
 ,"Status"                   
,"ProductCategoryKey"         
,"ProductCategoryAlternateKey"
,"EnglishProductCategoryName" 
,"EnglishProductSubcategoryName"
 from "DimProduct" prod
  left join cat_subcat 
  on prod."ProductSubcategoryKey" = cat_subcat."SubProductSubcategoryKey"
);

