-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v15 vs v14 by shawn.johnson@sqldbm.com *

CREATE TABLE SHAWN_ADWORKS.dim_DIM_RESELLER
(
 RESELLER_KEY           number(38,0) NOT NULL,
 from_dts               timestamp_ntz(9) NOT NULL,
 to_dts                 timestamp_ntz(9) NOT NULL,
 GEOGRAPHY_KEY          number(38,0),
 RESELLER_ALTERNATE_KEY varchar(15),
 PHONE                  varchar(25),
 BUSINESS_TYPE          varchar(20) NOT NULL,
 RESELLER_NAME          varchar(50) NOT NULL,
 NUMBER_EMPLOYEES       number(38,0),
 ORDER_FREQUENCY        varchar(1),
 ORDER_MONTH            number(38,0),
 FIRST_ORDER_YEAR       number(38,0),
 LAST_ORDER_YEAR        number(38,0),
 PRODUCT_LINE           varchar(50),
 ADDRESS_LINE_1         varchar(60),
 ADDRESS_LINE_2         varchar(60),
 ANNUAL_SALES           number(38,0),
 BANK_NAME              varchar(50),
 MIN_PAYMENT_TYPE       number(38,0),
 MIN_PAYMENT_AMOUNT     number(38,0),
 ANNUAL_REVENUE         number(38,0),
 YEAR_OPENED            number(38,0),
 ld_dt                  varchar(50) NOT NULL, 
 load_dts               timestamp_ntz(9) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( RESELLER_KEY, from_dts )
);