-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v16 vs v15 by shawn.johnson@sqldbm.com *

-- Attention! Table SHAWN_ADWORKS.dim_DIM_RESELLER - column GEOGRAPHY_KEY: autoincrement/identity property cannot be changed. Snowflake doesn't support this syntax.