-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v18 vs v15 by shawn.johnson@sqldbm.com *

-- Attention! Table SHAWN_ADWORKS.dim_DIM_RESELLER - column GEOGRAPHY_KEY: autoincrement/identity property cannot be changed. Snowflake doesn't support this syntax.




CREATE TABLE SHAWN_ADWORKS.sat_FACT_RESELLER_SALES
(
 md5_hub_FACT_RESELLER_SALES binary NOT NULL,
 load_dts                    timestamp_ntz(9) NOT NULL,
 PRODUCT_KEY                 number(38,0) NOT NULL,
 RESELLER_KEY                number(38,0) NOT NULL,
 EMPLOYEE_KEY                number(38,0) NOT NULL,
 PROMOTION_KEY               number(38,0) NOT NULL,
 CURRENCY_KEY                number(38,0) NOT NULL,
 SALES_TERRITORY_KEY         number(38,0) NOT NULL,
 SALES_ORDER_NUMBER          varchar(20) NOT NULL,
 SALES_ORDER_LINE_NUMBER     number(38,0) NOT NULL,
 REVISION_NUMBER             number(38,0),
 ORDER_QUANTITY              number(38,0),
 UNIT_PRICE                  number(38,0),
 EXTENDED_AMOUNT             number(38,0),
 UNIT_PRICE_DISCOUNT_PCT     float,
 DISCOUNT_AMOUNT             float,
 PRODUCT_STANDARD_COST       number(38,0),
 TOTAL_PRODUCT_COST          number(38,0),
 SALES_AMOUNT                number(38,0),
 TAX_AMT                     number(38,0),
 FREIGHT                     number(38,0),
 CARRIER_TRACKING_NUMBER     varchar(25),
 CUSTOMER_PO_NUMBER          varchar(25),
 DATE_KEY                    number(38,0) NOT NULL,
 DKEY_1                      number(38,0) NOT NULL,
 DKEY_2                      number(38,0) NOT NULL,
 ld_dt                       varchar(50) NOT NULL, 
 hash_diff                   binary NOT NULL,
 rec_src                     varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_FACT_RESELLER_SALES, load_dts )
);

CREATE TABLE SHAWN_ADWORKS.lnk_FACT_RESELLER_SALES
(
 md5_lnk_FACT_RESELLER_SALES binary NOT NULL,
 md5_hub_FACT_RESELLER_SALES binary NOT NULL,
 load_dts                    timestamp_ntz(9) NOT NULL,
 rec_src                     varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_lnk_FACT_RESELLER_SALES )
);

CREATE TABLE SHAWN_ADWORKS.hub_FACT_RESELLER_SALES
(
 md5_hub_FACT_RESELLER_SALES binary NOT NULL,
 load_dts                    timestamp_ntz(9) NOT NULL,
 rec_src                     varchar(16777216) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( md5_hub_FACT_RESELLER_SALES )
);