-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v23 vs v19 by shawn.johnson@sqldbm.com *

CREATE TAG PII;

ALTER TABLE shawn_adworks.dim_dim_department_group
    ALTER COLUMN department_group_name   SET TAG PII = '';