-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v28 vs v22 by shawn.johnson@sqldbm.com *

ALTER TABLE shawn_adworks.dim_department_group
    ADD COLUMN new varchar(50) NOT NULL;