-- ****************************** SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: AdWorks_Global, v32 vs v27 by shawn.johnson@sqldbm.com *

ALTER TABLE shawn_adworks.dim_product_subcategory
    ADD COLUMN new varchar(50) NOT NULL;