-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: BRONZE, v4 vs v3 by shawn.johnson+demo@sqldbm.com *

-- Attention! Cannot change column data type.

ALTER TABLE table_10
    ALTER COLUMN name SET DATA TYPE https://sqldbm_partner.snowflakecomputing.com/;

ALTER TABLE table_10
    ADD COLUMN new https://sqldbm_partner.snowflakecomputing.com/ NOT NULL;