-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.DimProductSubcategory
CREATE TABLE SHAWN_ADWORKS.DimProductSubcategory
(
 ProductSubcategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductSubcategoryAlternateKey number(38,0),
 EnglishProductSubcategoryName  varchar(50) NOT NULL,
 SpanishProductSubcategoryName  varchar(50) NOT NULL,
 FrenchProductSubcategoryName   varchar(50) NOT NULL,
 ProductCategoryKey             number(38,0),
 CONSTRAINT PK_DimProductSubcategory PRIMARY KEY ( ProductSubcategoryKey ),
 CONSTRAINT FK_DimProductSubcategory_409 FOREIGN KEY ( ProductCategoryKey ) REFERENCES SHAWN_ADWORKS.DimProductCategory ( ProductCategoryKey )
);
