-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.DimProductCategory
CREATE TABLE SHAWN_ADWORKS.DimProductCategory
(
 ProductCategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductCategoryAlternateKey number(38,0),
 EnglishProductCategoryName  varchar(50) NOT NULL,
 SpanishProductCategoryName  varchar(50) NOT NULL,
 FrenchProductCategoryName   varchar(50) NOT NULL,
 CONSTRAINT PK_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);
