-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.DimAccount
CREATE TABLE SHAWN_ADWORKS.DimAccount
(
 AccountKey                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 ParentAccountKey              number(38,0) COMMENT 'Identifier of parent Account',
 AccountCodeAlternateKey       number(38,0),
 ParentAccountCodeAlternateKey number(38,0),
 AccountDescription            varchar(50),
 AccountType                   varchar(50),
 Operator                      varchar(50),
 CustomMembers                 varchar(300),
 ValueType                     varchar(50),
 CustomMemberOptions           varchar(200),
 CONSTRAINT PK_DimAccount PRIMARY KEY ( AccountKey ) RELY
)
COMMENT = 'Holds all Account information';
