-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.FactResellerSales
CREATE TABLE SHAWN_ADWORKS.FactResellerSales
(
 ProductKey            number(38,0) NOT NULL,
 OrderDateKey          number(38,0) NOT NULL,
 DueDateKey            number(38,0) NOT NULL,
 ShipDateKey           number(38,0) NOT NULL,
 ResellerKey           number(38,0) NOT NULL,
 EmployeeKey           number(38,0) NOT NULL,
 PromotionKey          number(38,0) NOT NULL,
 CurrencyKey           number(38,0) NOT NULL,
 SalesTerritoryKey     number(38,0) NOT NULL,
 SalesOrderNumber      varchar(20) NOT NULL,
 SalesOrderLineNumber  number(38,0) NOT NULL,
 RevisionNumber        number(38,0),
 OrderQuantity         number(38,0),
 UnitPrice             number(38,0),
 ExtendedAmount        number(38,0),
 UnitPriceDiscountPct  float,
 DiscountAmount        float,
 ProductStandardCost   number(38,0),
 TotalProductCost      number(38,0),
 SalesAmount           number(38,0),
 TaxAmt                number(38,0),
 Freight               number(38,0),
 CarrierTrackingNumber varchar(25),
 CustomerPONumber      varchar(25),
 CONSTRAINT FK_FactResellerSales_445 FOREIGN KEY ( ProductKey ) REFERENCES SHAWN_ADWORKS.DimProduct ( ProductKey ),
 CONSTRAINT FK_FactResellerSales_447 FOREIGN KEY ( ResellerKey ) REFERENCES SHAWN_ADWORKS.DimReseller ( ResellerKey ),
 CONSTRAINT FK_FactResellerSales_449 FOREIGN KEY ( EmployeeKey ) REFERENCES SHAWN_ADWORKS.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_FactResellerSales_451 FOREIGN KEY ( PromotionKey ) REFERENCES SHAWN_ADWORKS.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactResellerSales_453 FOREIGN KEY ( CurrencyKey ) REFERENCES SHAWN_ADWORKS.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactResellerSales_455 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES SHAWN_ADWORKS.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactResellerSales_457 FOREIGN KEY ( OrderDateKey ) REFERENCES SHAWN_ADWORKS.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_459 FOREIGN KEY ( DueDateKey ) REFERENCES SHAWN_ADWORKS.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_461 FOREIGN KEY ( ShipDateKey ) REFERENCES SHAWN_ADWORKS.DimDate ( DateKey )
)
COMMENT = 'Fact data of Reseller Sales';
