-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.FactProductInventory
CREATE TABLE SHAWN_ADWORKS.FactProductInventory
(
 ProductKey   number(38,0) NOT NULL,
 DateKey      number(38,0) NOT NULL,
 MovementDate date NOT NULL,
 UnitCost     number(38,0) NOT NULL,
 UnitsIn      number(38,0) NOT NULL,
 UnitsOut     number(38,0) NOT NULL,
 UnitsBalance number(38,0) NOT NULL,
 CONSTRAINT FK_FactProductInventory_443 FOREIGN KEY ( DateKey ) REFERENCES SHAWN_ADWORKS.DimDate ( DateKey )
);
