-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.NewFactCurrencyRate
CREATE TABLE SHAWN_ADWORKS.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(3),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  number(38,0),
 DateKey      number(38,0),
 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES SHAWN_ADWORKS.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES SHAWN_ADWORKS.DimDate ( DateKey )
);
