-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: AdWorksGitDemo by shawn.johnson+demo@sqldbm.com *
-- ************************************** SHAWN_ADWORKS.ChildDemo
CREATE TABLE SHAWN_ADWORKS.ChildDemo
(
 ScenarioKey number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 CreatedBy   varchar(50) NOT NULL,
 CreatedDate timestamp_ntz(9) NOT NULL,
 UpdatedDate timestamp_ntz(9) NOT NULL,
 UpdatedBy   varchar(50) NOT NULL,
 CONSTRAINT PK_664 PRIMARY KEY ( ScenarioKey ) RELY,
 CONSTRAINT FK_661 FOREIGN KEY ( ScenarioKey ) REFERENCES SHAWN_ADWORKS.DimScenario ( ScenarioKey ) RELY
);
